on:
  push:
    branches:
      - master
name: CD
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: eltelemaco/azureaks:${{ github.sha }}
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'
      - name: Set up Kustomize      
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
          ls -la $HOME/.kube/config
          kubectl --kubeconfig $HOME/.kube/config
          kubectl config view
          kubectl get nodes
      - name: Get Namespace
        run: |
          kubectl get namespace ${{ vars.NAMESPACE }} -o name || kubectl create namespace ${{ vars.NAMESPACE }}
      
  
  create-namespace:
    name: create namespace
    runs-on: ubuntu-latest
    needs: docker    
    steps:
    - name: verify namespace
      uses: actions-hub/kubectl@master
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
      with:        
        args: get namespace ${{ vars.NAMESPACE }} -o name || create namespace ${{ vars.NAMESPACE }}
        

  deploy-to-cluster:
    name: deploy to cluster
    runs-on: ubuntu-latest
    needs: create-namespace
    steps:
    -
      name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: -n ${{ vars.NAMESPACE }} set image --record deployment/prueba-gha prueba-gha=eltelemaco/azureaks:${{ github.sha }}
    -
      name: verify deployment
      uses: steebchen/kubectl@v2.0.0
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        KUBECTL_VERSION: "1.28"
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: -n ${{ vars.NAMESPACE }} rollout status deployment/prueba-gha
